PRAGMA foreign_keys = ON;

ALTER TABLE orders ADD COLUMN tip_amount REAL NOT NULL DEFAULT 0.0;
ALTER TABLE tickets ADD COLUMN tip_amount REAL NOT NULL DEFAULT 0.0;
ALTER TABLE config ADD COLUMN tips_enabled BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE config ADD COLUMN tip_percentages TEXT NOT NULL DEFAULT '10,15,20';
