services:
  phoenixd:
    image: acinq/phoenixd:latest
    container_name: phoenixd
    restart: unless-stopped
    networks:
      - default
    volumes:
      - phoenixd_datadir:/phoenix/.phoenix
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  ambrosia:
    build: server/
    image: ambrosia
    container_name: ambrosia
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9154:9154"
      - "9443:9443"
    volumes:
      - ambrosia_datadir:/home/ambrosia/.Ambrosia-POS
      - phoenixd_datadir:/home/ambrosia/.phoenix
    depends_on:
      - phoenixd
    user: "ambrosia:ambrosia"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:exec,size=100m
  ambrosia-client:
    build:
      context: client/
      args:
        NEXT_PUBLIC_PORT_API: "9154"
    image: ambrosia-client
    container_name: ambrosia-client
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - ambrosia
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://ambrosia:9154
      NEXT_PUBLIC_PORT_API: "9154"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    user: "node:node"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:exec,size=100m

volumes:
  phoenixd_datadir: 
  ambrosia_datadir:
